{{- if and (ne .Values.config.accessKeyId "") (ne .Values.config.secretAccessKey "") (eq .Values.secretName "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dyndns-route53.fullname" . }}
  labels:
    {{- include "dyndns-route53.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.config.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.config.secretAccessKey | b64enc }}
{{- end }}
