secretName: dyndns-route53-custom-secret

config:
  zoneId: EXAMPLEZONE
  fqdn: test.example.com
  dryRun: true

securityContext:
  runAsUser: 8888
  runAsNonRoot: true

resources:
  limits:
    cpu: 100m
    memory: 16Mi
  requests:
    cpu: 10m
    memory: 8Mi
